// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeieapxzpuzcbuwkjspm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplaWVhcHh6cHV6Y2J1d2tqc3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjQwMjMsImV4cCI6MjA3NjA0MDAyM30.cB_ENgjfZK_sfJL2Pmf7LdOXUhDVc1nCl747Pjtdg3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});